// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, id pgtype.UUID) error
	GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListProducts(ctx context.Context) ([]Product, error)
	PlaceOrder(ctx context.Context, arg PlaceOrderParams) (Order, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
